version: '3.4'

services:
  flask-app:
    image: flask-app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports: 
      - "5000:5000"
    volumes: 
      - "./:/app"
    expose: 
      - 5000

